### ISSUE TITLE
Client render crash with barrel

### ISSUE THREAD

**Issue by Monster-Zer0** [LordDeatHunter/FabricaeExNihilo#39]
https://aofpaste.com/odesuzuyax.md

will cause client to crash

the specific coordinates in this report refer to an oak barrel.

**Comment by MattiDragon** [comment]
Let me guess. You have sodium, but not indium installed. Please reopen if indium doesn't fix it

**Comment by MattiDragon** [comment]
Wait, this might be a porting lib incompatability. Full logs and mod list would be nice

**Comment by MattiDragon** [comment]
After more research I don't see any relation to FEN. However, it could be doing things porting lib doesn't expect in some weird way. Mod list would really be important

**Comment by ValeTheVioletMote** [comment]
I had a similar issue the moment I placed grass seeds in a crucible - installing Indium worked. Here was my original error if it helps:

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-01-03 18:23:44
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.renderFluidVolume(CrucibleBlockEntityRenderer.java:67)
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.render(CrucibleBlockEntityRenderer.java:45)
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.method_3569(CrucibleBlockEntityRenderer.java:21)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$eaa000$onRenderTileEntities(class_761.java:16132)
	at net.minecraft.class_761.method_22710(class_761.java:1364)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.renderFluidVolume(CrucibleBlockEntityRenderer.java:67)
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.render(CrucibleBlockEntityRenderer.java:45)
	at wraith.fabricaeexnihilo.client.renderers.CrucibleBlockEntityRenderer.method_3569(CrucibleBlockEntityRenderer.java:21)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$eaa000$onRenderTileEntities(class_761.java:16132)
	at net.minecraft.class_761.method_22710(class_761.java:1364)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Block Entity Details --
Details:
	Name: fabricaeexnihilo:crucible // wraith.fabricaeexnihilo.modules.crucibles.CrucibleBlockEntity
	Block: Block{fabricaeexnihilo:oak_crucible}
	Block location: World: (-205,63,829), Section: (at 3,15,13 in -13,3,51; chunk contains blocks -208,-64,816 to -193,319,831), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Block: Block{fabricaeexnihilo:oak_crucible}
	Block location: World: (-205,63,829), Section: (at 3,15,13 in -13,3,51; chunk contains blocks -208,-64,816 to -193,319,831), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$eaa000$onRenderTileEntities(class_761.java:16132)
	at net.minecraft.class_761.method_22710(class_761.java:1364)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['ValeVioletMote'/48, l='ClientLevel', x=-203.83, y=64.00, z=829.41]]
	Chunk stats: 1024, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (149,69,343), Section: (at 5,5,7 in 9,4,21; chunk contains blocks 144,-64,336 to 159,319,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 208835 game time, 219751 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Crops-3D_MC1.19_v1.2.0.zip, FreshAnimations_v1.7.zip, Hyper+realistic+sky+[1.7-1.19].zip, Round-Trees-7.0-1.19+.zip, Stay_True_1.19.zip, wilderwild/new_main_menu, nosplashtext.zip, KubeJS Resource Pack [assets]
```

**Comment by MattiDragon** [comment]
Installing indium is the fix, not a workaround. Sodium doesn't support the render api FEN uses and indium adds it. Native sodium support is not planned as its unnecessary because some other mod will require indium anyways.
